import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { UMAP } from 'umap-js';

// ──────────────────────────────────────────────────────────────────────
// Lazy-init at first call. Two projectors per stage:
//   - PCA-2:   linear, fit by stacking library embeddings and grabbing the
//              top-2 eigenvectors of the centered covariance via power iteration.
//   - UMAP-2:  non-linear, fit using umap-js on the library embeddings, then
//              transform(new_embedding) projects new playback windows into
//              the same 2D space (~10-50ms in-process).
// 30 points per stage is on the low end for UMAP; the layout is still useful
// for a "normal vs attack" demo visual, but exact distances shouldn't be
// over-interpreted.
// ──────────────────────────────────────────────────────────────────────

let STATE = null;
let STATE_ERROR = null;

function loadLibrary() {
	const path = resolve('data/knn-library.json');
	if (!existsSync(path)) {
		throw new Error(
			'Missing data/knn-library.json — run `node scripts/build-knn-library.js` first.'
		);
	}
	return JSON.parse(readFileSync(path, 'utf-8'));
}

// Subtract row-wise mean from a [n × d] matrix (mutates).
function centerInPlace(mat, mean) {
	for (let i = 0; i < mat.length; i++) {
		const row = mat[i];
		for (let j = 0; j < row.length; j++) row[j] -= mean[j];
	}
}

function meanVec(mat) {
	const d = mat[0].length;
	const out = new Float64Array(d);
	for (let i = 0; i < mat.length; i++) {
		const row = mat[i];
		for (let j = 0; j < d; j++) out[j] += row[j];
	}
	for (let j = 0; j < d; j++) out[j] /= mat.length;
	return out;
}

// Compute X^T X · v for centered X (n × d) and vector v (d). Avoids materialising
// the d × d covariance matrix (which would be ~50 MB for d=9216).
function covMul(X, v) {
	const n = X.length;
	const d = v.length;
	const Xv = new Float64Array(n);
	for (let i = 0; i < n; i++) {
		const row = X[i];
		let s = 0;
		for (let j = 0; j < d; j++) s += row[j] * v[j];
		Xv[i] = s;
	}
	const out = new Float64Array(d);
	for (let i = 0; i < n; i++) {
		const xv = Xv[i];
		const row = X[i];
		for (let j = 0; j < d; j++) out[j] += row[j] * xv;
	}
	return out;
}

function norm(v) {
	let s = 0;
	for (let i = 0; i < v.length; i++) s += v[i] * v[i];
	return Math.sqrt(s);
}

function scaleInPlace(v, s) {
	for (let i = 0; i < v.length; i++) v[i] *= s;
}

function dot(a, b) {
	let s = 0;
	for (let i = 0; i < a.length; i++) s += a[i] * b[i];
	return s;
}

// Power iteration for the top eigenvector of X^T X. Deflate to get the 2nd.
function powerIter(X, d, iters = 80) {
	let v = new Float64Array(d);
	// Seed: deterministic small random-like values (avoid all-zero gradients).
	for (let i = 0; i < d; i++) v[i] = Math.sin(i + 1);
	scaleInPlace(v, 1 / norm(v));
	for (let it = 0; it < iters; it++) {
		const Av = covMul(X, v);
		const n = norm(Av);
		if (n < 1e-12) break;
		scaleInPlace(Av, 1 / n);
		v = Av;
	}
	return v;
}

function fitPCA(rawMatrix) {
	const d = rawMatrix[0].length;
	// Copy to Float64 and center.
	const X = rawMatrix.map((row) => Float64Array.from(row));
	const mean = meanVec(X);
	centerInPlace(X, mean);

	const v1 = powerIter(X, d);
	// Deflate: subtract projection on v1 from each row, then second power iter.
	for (let i = 0; i < X.length; i++) {
		const row = X[i];
		const c = dot(row, v1);
		for (let j = 0; j < d; j++) row[j] -= c * v1[j];
	}
	const v2 = powerIter(X, d);
	return { mean, axes: [v1, v2] };
}

function projectPCAVec({ mean, axes }, vec) {
	let x = 0;
	let y = 0;
	const v1 = axes[0];
	const v2 = axes[1];
	for (let i = 0; i < vec.length; i++) {
		const c = vec[i] - mean[i];
		x += c * v1[i];
		y += c * v2[i];
	}
	return [x, y];
}

// Optional: a precomputed embedding pool sampled from the inference timeline.
// If present, projected through the same per-stage PCA/UMAP and rendered as a
// background scatter cloud in the embedding-viz panel. Generated by
// scripts/build-inference-sample.js; missing file is a no-op.
function loadInferenceSample() {
	const path = resolve('data/inference-sample.json');
	if (!existsSync(path)) return null;
	try {
		return JSON.parse(readFileSync(path, 'utf-8'));
	} catch {
		return null;
	}
}

async function initOnce() {
	if (STATE || STATE_ERROR) return;
	try {
		const lib = loadLibrary();
		const inference = loadInferenceSample();
		const stages = {};
		for (const [stageId, entry] of Object.entries(lib.stages)) {
			const raw = entry.embeddings.map((e) => e.vec);
			const labels = entry.embeddings.map((e) => e.label);

			const pca = fitPCA(raw);
			const pcaCoords = raw.map((vec) => projectPCAVec(pca, vec));

			// umap-js: 30 points needs nNeighbors <= ~15; cap it.
			const umap = new UMAP({
				nComponents: 2,
				nNeighbors: Math.min(15, raw.length - 1),
				minDist: 0.1,
				random: seededRandom(42)
			});
			const umapCoords = umap.fit(raw);

			// Leave-one-out KNN accuracy in the FULL embedding space (not 2D).
			// Tells the user whether the classifier actually works for this stage,
			// independent of how cleanly the 2D projection separates the classes.
			const looAccuracy = leaveOneOutKNN(raw, labels, 3);

			// Project the optional inference-sample pool through the same PCA/UMAP.
			let inferencePoints = null;
			const infStage = inference?.stages?.[stageId];
			if (infStage?.embeddings?.length) {
				inferencePoints = { pca: [], umap: [] };
				// umap.transform takes an array of vectors and returns 2D coords.
				const vecs = infStage.embeddings.map((e) => e.vec);
				const labelsInf = infStage.embeddings.map((e) => e.label);
				const rowOffsets = infStage.embeddings.map((e) => e.rowOffset);
				const umapMapped = umap.transform(vecs);
				for (let i = 0; i < vecs.length; i++) {
					const [px, py] = projectPCAVec(pca, vecs[i]);
					inferencePoints.pca.push({ x: px, y: py, label: labelsInf[i], rowOffset: rowOffsets[i] });
					const [ux, uy] = umapMapped[i] ?? [null, null];
					inferencePoints.umap.push({ x: ux, y: uy, label: labelsInf[i], rowOffset: rowOffsets[i] });
				}
			}

			stages[stageId] = {
				columns: entry.columns,
				labels,
				pca,
				umap,
				library: {
					pca: pcaCoords.map(([x, y], i) => ({ x, y, label: labels[i] })),
					umap: umapCoords.map(([x, y], i) => ({ x, y, label: labels[i] }))
				},
				inferenceSample: inferencePoints,
				looAccuracy
			};
		}
		STATE = { config: lib.config, stages };
	} catch (err) {
		STATE_ERROR = err;
	}
}

// Leave-one-out k-NN on the library: for each point, predict its label using
// the k nearest neighbours from the REMAINING points, then report accuracy.
// Operates on the full-dim embeddings (the same space KNN classification uses),
// so this is a direct measure of "does the classifier work for this stage."
function leaveOneOutKNN(raw, labels, k) {
	const n = raw.length;
	let correct = 0;
	for (let i = 0; i < n; i++) {
		const target = raw[i];
		const truth = labels[i];
		const dists = [];
		for (let j = 0; j < n; j++) {
			if (j === i) continue;
			let s = 0;
			const other = raw[j];
			for (let d = 0; d < target.length; d++) {
				const diff = target[d] - other[d];
				s += diff * diff;
			}
			dists.push({ d: s, label: labels[j] });
		}
		dists.sort((a, b) => a.d - b.d);
		const top = dists.slice(0, k);
		const votes = {};
		for (const t of top) votes[t.label] = (votes[t.label] || 0) + 1;
		let winner = null;
		let max = -1;
		for (const [label, v] of Object.entries(votes)) {
			if (v > max) {
				max = v;
				winner = label;
			}
		}
		if (winner === truth) correct++;
	}
	return correct / n;
}

// Deterministic PRNG so UMAP layouts are stable across server restarts.
function seededRandom(seed) {
	let s = seed >>> 0;
	return function () {
		s = (s * 1664525 + 1013904223) >>> 0;
		return s / 4294967296;
	};
}

export async function ensureProjections() {
	await initOnce();
	if (STATE_ERROR) throw STATE_ERROR;
}

export async function getLibraryProjections() {
	await ensureProjections();
	const out = {};
	for (const [stageId, s] of Object.entries(STATE.stages)) {
		out[stageId] = {
			columns: s.columns,
			library: s.library,
			inferenceSample: s.inferenceSample,
			looAccuracy: s.looAccuracy
		};
	}
	return out;
}

// Project a flat embedding into 2D for a given stage. Returns { pca, umap }.
export async function projectEmbedding(stageId, embedding) {
	await ensureProjections();
	const s = STATE.stages[stageId];
	if (!s) throw new Error(`no projection for stage ${stageId}`);
	const pca = projectPCAVec(s.pca, embedding);
	// umap-js transform expects an array of arrays.
	const [umap] = s.umap.transform([Array.from(embedding)]);
	return { pca, umap };
}
